#name: ci
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    services:
#      postgres:
#        image: postgres:latest
#        env:
#          POSTGRES_USER: postgres
#          POSTGRES_PASSWORD: postgres
#          POSTGRES_DB: touchly
#        ports:
#          - 5432:5432
#        options: --name db
#    steps:
#      -
#        name: Checkout
#        uses: actions/checkout@v4
#      -
#        name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      -
#        name: Prepare Image Tags
#        run: |
#          echo "IMAGE_TAG=$(date +'%Y%m%d')-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
#          echo "IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}" >> $GITHUB_ENV
#      -
#        name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          push: true
#          tags: "${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
#      -
#        name: Start Container with api
#        uses: docker://${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
#        with:
#          args: /app/api -config /api/configs/config.api.example.yaml
#      -
#        name: Run Tests
#        run: |
#          npm install
#          npm run test
